name: sSurvivalGames
version: ${project.version}
author: Jul1an_K
depend: [Multiverse-Core]
main: me.jul1an_k.survivalgames.SurvivalGames


commands:
  survivalgames:
    description: The SurvivalGames Command.
    usage: /<command>
    aliases: [sg]